name: jlabeda_uniqcast_task
description: "Recruitment task for UniqCast - Jan Łabęda"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  build_runner: ^2.4.9
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.4.2+1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  freezed: ^2.4.7
  go_router: ^13.2.3
  intl: ^0.19.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets: 
    - assets/images/
  fonts:
    - family: Karla
      fonts:
        - asset: assets/font/Karla-VariableFont_wght.ttf
